baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'The Joy of Thinking Foundation'

collections:
  services:
    output: true
    permalink: /services/:path/
  founders:
    output: true
    permalink: /founders/:path/
  teachers:
    output: true
    permalink: /teachers/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/
  flying_quotes:
    output: true
    permalink: /flying_quotes/:path/
  benefactors:
    output: true
    permalink: /benefactors/:path/
    

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
  - jekyll-menus
  - jekyll-google-photos
